In [1]:
import numpy as np
import pandas as pd

In [2]:
a=np.array([[5,4,8],[6,-8,1],[7,9,-10]])
print(a)
#Creating a 3x3 matrix

[[  5   4   8]
 [  6  -8   1]
 [  7   9 -10]]


In [3]:
#Calculating the determinant of the matrix

deta=np.linalg.det(a)
print(deta)

1503.0


In [4]:
#Calculating the inverse of the matrix

inva=np.linalg.inv(a)
print(inva)

[[ 0.04723886  0.07451763  0.04524285]
 [ 0.04457751 -0.07052562  0.02860945]
 [ 0.07318696 -0.01131071 -0.0425815 ]]


In [5]:
#Calculating eigenvalues and eigenvectors of the matrix

eigenvalues,eigenvectors=np.linalg.eig(a)

In [6]:
#Printing eigenvalues
print(eigenvalues)

[ 10.40333852+0.j         -11.70166926+2.74659603j
 -11.70166926-2.74659603j]


In [7]:
#Printing eigenvectors
print(eigenvectors)

[[ 0.85325123+0.j         -0.40068187-0.15373488j -0.40068187+0.15373488j]
 [ 0.30131228+0.j          0.15848238+0.36677949j  0.15848238-0.36677949j]
 [ 0.42564451+0.j          0.81004677+0.j          0.81004677-0.j        ]]
